### ISSUE TITLE
Bug: unable to access "localhost:port"

### ISSUE THREAD

**Issue by yacmov** [NM-TAFE/dip-programming-prj-advanced-gui-architect#10]
> [!note]  
> **This issue doesn’t occur when I try to use it with PyCharm**
> **But With VS Code has problem** 

# System
|     Main system      | Test system using different IDE | Test system using different platform |
| :------------------: | :-----------------------------: | :----------------------------------: |
|        macOS        |              macOS             |            Windows 11 Arm            |
|  VS Code |             Pycharm             |          VS Code          |

# Description

## Understanding the Problem
- **Port Conflict**: As I mentioned, common port usage by VS Code extensions and macOS(3000, 5000, etc) can lead to conflicts. I've Identified can use port 5001 in both systems. 
- **Configuration File Issue**: The Inability to access the application suggests the configuration file `config.example.ini` might not be read correctly due to a path issue.
- **Path Handling Differences**: While PyCharm and VS Code handle paths slightly differently.

**Screenshot 1** - using port 5000 both PyCharm and VS Code on macOS

<img width="849" alt="image" src="https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/e91be738-6913-4268-9cae-6ef81e7376e7">

**Screenshot 2** - using port 5001 with VS Code on macOS
ErrorCode: `FileNotFoundError`

<img width="849" alt="image" src="https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/b17af06d-8474-4023-8636-6efbe262bc28">

**Screenshot 3** - using port 5001 with PyCharm on macOS
<img width="849" alt="image" src="https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/eac855cd-a16b-4230-a7e6-0e93fa155dd8">

### Solutions

1. Verify Port Usage:
- Use alternative port ex: 5001, 5002 etc.
- To avoid error code added code to check platform then if windows, use 5000 and macOS/Linux use 5002

2. Resolve Configuration File Path:

**Screenshot 4** - problem with relative path with VS Code on macOS
![image](https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/6e3e1a83-e7ce-4f29-9c11-60bebac12a64)

- Change to absolute path will solve the problem.

**app.py**
![image](https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/8fd2751b-ccce-4c0d-a0b5-2c406defc7d6)

**utils.py**
![image](https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/ace94705-b8a5-4d40-a968-29562f210f93)
![image](https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/assets/130235299/419bcbbd-6630-4621-8121-f23ac5eb9522)

3. [Pull requests](https://github.com/NM-TAFE/dip-programming-prj-advanced-gui-architect/pull/11)

**Comment by rafrafavi** [comment]
can you include the specific error message and/or a screenshot? Have you triaged which area of the code is likely to be affected?

**Comment by adikal25** [comment]
Try changing your port number to 5001 since 5000 might already be in use
python run app.py --port 5001

**Comment by yacmov** [comment]
> can you include the specific error message and/or a screenshot? Have you triaged which area of the code is likely to be affected?

@rafrafavi I added more information to the top page  with screenshots. And also find which area of code will be affected. Could you please have a look for me?



> Try changing your port number to 5001 since 5000 might already be in use python run app.py --port 5001

@adikal25 Yes, I am using 5001 and 5002 instead of 5000 to run the app. And I thought if the app found macOS or Linux straightaway run 5001 or 5002 instead of run 5000 with error. How do you think?

**Comment by adikal25** [comment]
> > can you include the specific error message and/or a screenshot? Have you triaged which area of the code is likely to be affected?
> 
> @rafrafavi I added more information to the top page with screenshots. And also find which area of code will be affected. Could you please have a look for me?
> 
> > Try changing your port number to 5001 since 5000 might already be in use python run app.py --port 5001
> 
> @adikal25 Yes, I am using 5001 and 5002 instead of 5000 to run the app. And I thought if the app found macOS or Linux straightaway run 5001 or 5002 instead of run 5000 with error. How do you think?

> @rafrafavi with this code it should solve the above problem 
if __name__ == '__main__':
    port = 5000
    if os.name == 'posix': 
        port = 5001  # or 5002 as needed
    app.run(port=port)
