### ISSUE TITLE
Issue #2 - Incomplete SetUp/Installation Instructions

### ISSUE THREAD

**Issue by Rumsie-Grimshaw** [NM-TAFE/dip-programming-prj-advanced-gui-architect#5]
Issue Description: 
The installation / SetUp instructions in the README.md file is incomplete and should be updated.

**Comment by rafrafavi** [comment]
can you be more specific in terms of how it is incomplete and what problems were encountered?

**Comment by Rumsie-Grimshaw** [comment]
Issue Description:
The 5th step of the installation setup is detailed as: 
  ```bash
5. ...rest of installation steps here
   ```

Issue: 
The original setup instructions do not mention the following as requirements for the project to run correctly:
- Running the program from app/app.py
- Download and Installation of the Tesseract OCR Library
- An AI API Key (example; OpenAI) - (requires user account)
- Setting up app/config.ini

Although the project runs with the current instructions detailed in the README.md - they do not set the project up to be usable initially. I believe the points listed above are good candidates to be added to the README.md file. Possibly adding links to assist users in setting up the project. 

Note: 
This issue was logged prior to the 404 Error being resolved and may no longer be necessary - pending that the projects README.md is also updated.
